### ISSUE TITLE
Kingdom III Save Corrupt

### ISSUE THREAD

**Issue by gigantlui** [Xeeynamo/KH3SaveEditor#94] opened 2020-08-12 19:00 UTC
Hey there,

today I spent many hours trying to make the KH3 Save Editor work, but everytime I edit the save, the file would be corrupted and then the complete savedata would be deleted.

I am Using a PS4 with 6.72 and KH3 (CUSA12025)
1. I would use "Playstation-4-Save-Mounter_v1.6" to decrypt the KH3 save
2. Use FTP to copy it to my desktop
3. Edit Save with "KingdomSaveEditor-12.0.exe" (from here https://github.com/Xeeynamo/KH3SaveEditor/releases)
4. Copy Save back using FTP and unmount with PS4SaveMounter back
5. When starting game I always get "save corrupted" message

When I do the same process without editing anything the mechanics with copying mounting etc. works fine with the raw save file and I get no error. But as soon as I open the save with the editor and save it again (even without editing anything) the save is recognized as corrupted. Therefore it must be some bug with the editor in my understanding.

Here is a Dropbox Link with the original and the edited save (I didn't change anything, just opened and saved file, but after saving its for some reason corrupted).
https://www.dropbox.com/sh/x0zcs8doduqkbep/AAB4xnQlFx98zdkAOp-BD1LJa?dl=0

Best regards

**Comment by Xeeynamo** [comment] 2020-08-13 07:21
Duplicate of #85 . I am investigating but I already have an idea on why exactly this is happening. The Save Editor is not corrupting the save as it works with Save Wizard flawlessy.

**Closed by Xeeynamo** 2020-08-13 07:21 UTC
