### ISSUE TITLE
norton and windows bitprotector are reporting suspicious activity and removing it

### ISSUE THREAD

**Issue by dmcmillin** [Xeeynamo/KH3SaveEditor#32] opened 2020-04-10 18:35 UTC
when running it windows malware/protector and Norton and reporting suspicious issues and deleting the app. any reason why it would do that?

**Comment by Xeeynamo** [comment] 2020-04-10 19:53
This is a duplicate of #29 . Sorry if this is happening. You can whitelist the program from your antivirus as it is safe:
https://www.virustotal.com/gui/file/6d2a843938d42f09ce8a8db7a1b36e9002a8a9504ad18455d3862f65a096749b/detection

**Closed by Xeeynamo** 2020-04-10 19:53 UTC
