### ISSUE TITLE
KH3 PC (Epic) Save File Not Recognized

### ISSUE THREAD

**Issue by phoenixseven81** [Xeeynamo/KH3SaveEditor#151] opened 2021-04-03 15:37 UTC
* Game name: - KH3 (ver. 1.0.0.0-CL-1065258)
* Platform: -  PC (Epic)

I just downloaded the game (ver. 1.0.0.0-CL-1065258) and the latest save editor (ver. 1.15.0). I got to a point in the game where I could create a save. When I try to open it up in the editor, I get an error that says "The specified save game is not recognized. Be sure to have the latest version or that the save is decrypted or supported."

**Comment by Delta-473** [comment] 2021-04-03 15:39
KH3 for PC isn't supported yet.

**Comment by Delta-473** [comment] 2021-04-03 15:40
also duplicate of #147 :)

**Closed by Delta-473** 2021-04-03 15:40 UTC
Labels: enhancement
